### ISSUE TITLE
FailedPostStartHook in the poststart command

### ISSUE THREAD

**Issue by kouamdo** [infinitydon/5gcore-sctp-loadbalancer#1]
https://github.com/infinitydon/5gcore-sctp-loadbalancer/blob/31f125343e23b8bedd477dda210e77792ef77411/loxilb-helm-chart/templates/loxilb-statefulset.yaml#L47

hi  , i'm trying to find where the error coming from . Unfortunately i didn't see something

**Comment by kouamdo** [comment]
![image](https://github.com/infinitydon/5gcore-sctp-loadbalancer/assets/39982727/a168ff67-9192-4800-8f66-f5f8d46b59c6)
does it the problem?

**Comment by infinitydon** [comment]
Can you try again with the latest commit?
